name: Deploy Cloud Workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target Environment"
        required: true
        default: "development"
        type: choice
        options:
          - development
          - production
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write

jobs:
  determine_environment:
    name: "Determine Environment"
    runs-on: ubuntu-24.04
    outputs:
      environment: ${{ steps.get_env.outputs.environment }}
      dir: ${{ steps.get_env.outputs.dir }}
    steps:
      - id: get_env
        name: Set environment for this workflow run
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "environment=development" >> $GITHUB_OUTPUT
          else
            ENVIRONMENT="${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'production' || 'development') }}"
            echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
          fi

  deploy:
    name: "Deploy workflow"
    needs: determine_environment
    runs-on: ubuntu-24.04
    environment: ${{ needs.determine_environment.outputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"
        with:
          version: ">= 363.0.0"
          project_id: ${{ secrets.PROJECT_ID }}

      - name: "Deploy Cloud Workflow"
        run: |
          gcloud workflows deploy my-workflow \
            --source=./workflows/ingestion-main.yaml \
            --location=${{ secrets.PROJECT_REGION }} \
            --project=${{ secrets.PROJECT_ID }} \
            --set-env-vars=PROJECT_ID=${{ secrets.PROJECT_ID }},PROJECT_REGION=${{ secrets.PROJECT_REGION }}
